.

diff --git a/home/bin/initp b/home/bin/initp
--- a/home/bin/initp
+++ b/home/bin/initp
@@ -1,4 +1,13 @@
 #!/usr/bin/env sh
 
-nix flake init -t "github:the-nix-way/dev-templates#$1"
+if [ -z "$1" ]; then
+	echo "Please provide a template name"
+	exit 1
+fi
+
+if ! nix flake init -t "github:shardulbee/dev-templates#$1"; then
+	echo "Failed to initialize template"
+	exit 1
+fi
+
 direnv allow
