.

diff --git a/home/bin/log-codefocus b/home/bin/log-codefocus
--- a/home/bin/log-codefocus
+++ b/home/bin/log-codefocus
@@ -5,6 +5,12 @@
 # if not provided, default to 1 minute
 value=$(echo "scale=0; $1 / 60" | bc)
 
+# do not log if less than 1 minute
+if [ $value -lt 1 ]; then
+  echo "No need to log less than 1 minute. Exiting."
+  exit 1
+fi
+
 goal="codefocus"
 comment="Logged automatically by Pomodoro app"
 auth_token=$(op item get Beeminder --fields label="api_key")
@@ -13,3 +19,10 @@ curl -XPOST "https://www.beeminder.com/api/v1/users/turbochardo/goals/$goal/data
   -d auth_token="$auth_token" \
   -d value="$value" \
   -d comment="$comment"
+
+if [ $? -ne 0 ]; then
+  echo "Failed to log to Beeminder. Exiting."
+  exit 1
+else
+  echo "Logged $value minutes to Beeminder goal $goal"
+fi
