.

diff --git a/home/bin/tarsnap-backup b/home/bin/tarsnap-backup
--- a/home/bin/tarsnap-backup
+++ b/home/bin/tarsnap-backup
@@ -6,24 +6,23 @@ now=$(date +%Y-%m-%d_%H-%M-%S)
 name=${computer}-${now}
 
 directories=(
-    "$HOME/Library/Mobile Documents/com~apple~CloudDocs/Personal Documents"
-    "$HOME/Library/Mobile Documents/com~apple~CloudDocs/Family Documents/Taxes"
-    "$HOME/Library/Mobile Documents/com~apple~CloudDocs/Family Documents/Real Estate"
-    "$HOME/Library/Mobile Documents/com~apple~CloudDocs/Family Documents/Family/Bébé Baral"
-    "$HOME/Library/Mobile Documents/com~apple~CloudDocs/Family Documents/Receipts"
-    "$HOME/Library/Mobile Documents/com~apple~CloudDocs/Family Documents/Misc Documents"
-    "$HOME/Library/Mobile Documents/com~apple~CloudDocs/Family Documents/Will:POA:Mandate"
-    "$HOME/Library/Mobile Documents/com~apple~CloudDocs/Google Drive"
+    "/Volumes/Drive/Personal Documents"
+    "/Volumes/Drive/Family Documents"
 )
 
 for dir in "${directories[@]}"; do
     if [ -d "${dir}" ]; then
-        echo "Backing up: ${dir}"
+        echo "Backing up: ${dir}. Time: $(date)"
         /usr/local/bin/tarsnap -c \
-            --print-stats \
             -f "${name}-$(basename "$dir")" \
             -C "$(dirname "$dir")" \
             "$(basename "$dir")"
+
+        if [ $? -eq 0 ]; then
+            echo "Backup successful: ${dir}."
+        else
+            echo "Backup failed: ${dir}."
+        fi
         echo
     else
         echo "Directory not found: ${dir}"
